
// This file has been generated by the GUI designer. Do not modify.
namespace CommBug
{
	public partial class NumericalModelingDialog
	{
		private global::Gtk.Table tableMain;

		private global::Gtk.Image imageMain;

		private global::Gtk.Table tableFunction;

		private global::Gtk.Button buttonExponential;

		private global::Gtk.Button buttonGetData;

		private global::Gtk.Button buttonHyperbolic;

		private global::Gtk.Button buttonLinear;

		private global::Gtk.Table tableRange;

		private global::Gtk.Label labelEndArea;

		private global::Gtk.Label labelStartArea;

		private global::Gtk.SpinButton spinbuttonEnd;

		private global::Gtk.SpinButton spinbuttonStart;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CommBug.NumericalModelingDialog
			this.Name = "CommBug.NumericalModelingDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("曲线拟合分析");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CommBug.NumericalModelingDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "NumericalModelingDialog_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child NumericalModelingDialog_VBox.Gtk.Box+BoxChild
			this.tableMain = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tableMain.Name = "tableMain";
			this.tableMain.RowSpacing = ((uint)(6));
			this.tableMain.ColumnSpacing = ((uint)(6));
			// Container child tableMain.Gtk.Table+TableChild
			this.imageMain = new global::Gtk.Image ();
			this.imageMain.Name = "imageMain";
			this.tableMain.Add (this.imageMain);
			// Container child tableMain.Gtk.Table+TableChild
			this.tableFunction = new global::Gtk.Table (((uint)(5)), ((uint)(1)), false);
			this.tableFunction.Name = "tableFunction";
			this.tableFunction.RowSpacing = ((uint)(6));
			this.tableFunction.ColumnSpacing = ((uint)(6));
			// Container child tableFunction.Gtk.Table+TableChild
			this.buttonExponential = new global::Gtk.Button ();
			this.buttonExponential.CanFocus = true;
			this.buttonExponential.Name = "buttonExponential";
			this.buttonExponential.UseUnderline = true;
			this.buttonExponential.Label = global::Mono.Unix.Catalog.GetString ("指数分析");
			this.tableFunction.Add (this.buttonExponential);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tableFunction[this.buttonExponential]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableFunction.Gtk.Table+TableChild
			this.buttonGetData = new global::Gtk.Button ();
			this.buttonGetData.CanFocus = true;
			this.buttonGetData.Name = "buttonGetData";
			this.buttonGetData.UseUnderline = true;
			this.buttonGetData.Label = global::Mono.Unix.Catalog.GetString ("取样");
			this.tableFunction.Add (this.buttonGetData);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tableFunction[this.buttonGetData]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableFunction.Gtk.Table+TableChild
			this.buttonHyperbolic = new global::Gtk.Button ();
			this.buttonHyperbolic.CanFocus = true;
			this.buttonHyperbolic.Name = "buttonHyperbolic";
			this.buttonHyperbolic.UseUnderline = true;
			this.buttonHyperbolic.Label = global::Mono.Unix.Catalog.GetString ("双曲线分析");
			this.tableFunction.Add (this.buttonHyperbolic);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tableFunction[this.buttonHyperbolic]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableFunction.Gtk.Table+TableChild
			this.buttonLinear = new global::Gtk.Button ();
			this.buttonLinear.CanFocus = true;
			this.buttonLinear.Name = "buttonLinear";
			this.buttonLinear.UseUnderline = true;
			this.buttonLinear.Label = global::Mono.Unix.Catalog.GetString ("线性分析");
			this.tableFunction.Add (this.buttonLinear);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableFunction[this.buttonLinear]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableFunction.Gtk.Table+TableChild
			this.tableRange = new global::Gtk.Table (((uint)(1)), ((uint)(4)), false);
			this.tableRange.Name = "tableRange";
			this.tableRange.RowSpacing = ((uint)(6));
			this.tableRange.ColumnSpacing = ((uint)(6));
			// Container child tableRange.Gtk.Table+TableChild
			this.labelEndArea = new global::Gtk.Label ();
			this.labelEndArea.Name = "labelEndArea";
			this.labelEndArea.LabelProp = global::Mono.Unix.Catalog.GetString ("终止域");
			this.tableRange.Add (this.labelEndArea);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tableRange[this.labelEndArea]));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRange.Gtk.Table+TableChild
			this.labelStartArea = new global::Gtk.Label ();
			this.labelStartArea.Name = "labelStartArea";
			this.labelStartArea.LabelProp = global::Mono.Unix.Catalog.GetString ("起始域");
			this.tableRange.Add (this.labelStartArea);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.tableRange[this.labelStartArea]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRange.Gtk.Table+TableChild
			this.spinbuttonEnd = new global::Gtk.SpinButton (0, 1000, 1);
			this.spinbuttonEnd.CanFocus = true;
			this.spinbuttonEnd.Name = "spinbuttonEnd";
			this.spinbuttonEnd.Adjustment.PageIncrement = 10;
			this.spinbuttonEnd.ClimbRate = 1;
			this.spinbuttonEnd.Numeric = true;
			this.spinbuttonEnd.Value = 100;
			this.tableRange.Add (this.spinbuttonEnd);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableRange[this.spinbuttonEnd]));
			w9.LeftAttach = ((uint)(3));
			w9.RightAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableRange.Gtk.Table+TableChild
			this.spinbuttonStart = new global::Gtk.SpinButton (0, 1000, 1);
			this.spinbuttonStart.CanFocus = true;
			this.spinbuttonStart.Name = "spinbuttonStart";
			this.spinbuttonStart.Adjustment.PageIncrement = 10;
			this.spinbuttonStart.ClimbRate = 1;
			this.spinbuttonStart.Numeric = true;
			this.tableRange.Add (this.spinbuttonStart);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableRange[this.spinbuttonStart]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.tableFunction.Add (this.tableRange);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableFunction[this.tableRange]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.tableMain.Add (this.tableFunction);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableMain[this.tableFunction]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.tableMain);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1[this.tableMain]));
			w13.Position = 0;
			// Internal child CommBug.NumericalModelingDialog.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "NumericalModelingDialog_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child NumericalModelingDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14[this.buttonOk]));
			w15.Expand = false;
			w15.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 640;
			this.DefaultHeight = 416;
			this.Show ();
			this.buttonLinear.Clicked += new global::System.EventHandler (this.OnButtonLinearClicked);
			this.buttonHyperbolic.Clicked += new global::System.EventHandler (this.OnButtonHyperbolicClicked);
			this.buttonGetData.Clicked += new global::System.EventHandler (this.OnButtonGetDataClicked);
			this.buttonExponential.Clicked += new global::System.EventHandler (this.OnButtonExponentialClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
