
// This file has been generated by the GUI designer. Do not modify.
namespace CommBug
{
	public partial class AboutWindow
	{
		private global::Gtk.Notebook notebookAboutWindow;

		private global::Gtk.Table tableInfo;

		private global::Gtk.Image imageInfo;

		private global::Gtk.Label labelTabInfo;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CommBug.AboutWindow
			this.Name = "CommBug.AboutWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("关于本程序");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CommBug.AboutWindow.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "AboutWindow_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child AboutWindow_VBox.Gtk.Box+BoxChild
			this.notebookAboutWindow = new global::Gtk.Notebook ();
			this.notebookAboutWindow.CanFocus = true;
			this.notebookAboutWindow.Name = "notebookAboutWindow";
			this.notebookAboutWindow.CurrentPage = 0;
			// Container child notebookAboutWindow.Gtk.Notebook+NotebookChild
			this.tableInfo = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tableInfo.Name = "tableInfo";
			this.tableInfo.RowSpacing = ((uint)(6));
			this.tableInfo.ColumnSpacing = ((uint)(6));
			// Container child tableInfo.Gtk.Table+TableChild
			this.imageInfo = new global::Gtk.Image ();
			this.imageInfo.Name = "imageInfo";
			this.tableInfo.Add (this.imageInfo);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.imageInfo]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			this.notebookAboutWindow.Add (this.tableInfo);
			// Notebook tab
			this.labelTabInfo = new global::Gtk.Label ();
			this.labelTabInfo.Name = "labelTabInfo";
			this.labelTabInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("信息(_I)");
			this.labelTabInfo.UseUnderline = true;
			this.notebookAboutWindow.SetTabLabel (this.tableInfo, this.labelTabInfo);
			this.labelTabInfo.ShowAll ();
			w1.Add (this.notebookAboutWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1[this.notebookAboutWindow]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child CommBug.AboutWindow.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "AboutWindow_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child AboutWindow_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonOk]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 344;
			this.Show ();
		}
	}
}
