
// This file has been generated by the GUI designer. Do not modify.
namespace CommBug
{
	public partial class AboutWindow
	{
		private global::Gtk.Notebook notebookAboutWindow;

		private global::Gtk.Alignment alignmentInfo;

		private global::Gtk.Table tableInfo;

		private global::Gtk.Image imageInfo;

		private global::Gtk.ScrolledWindow scrolledwindowInfo;

		private global::Gtk.Label labelInfo;

		private global::Gtk.Label labelTabInfo;

		private global::Gtk.Alignment alignmentAuthor;

		private global::Gtk.Table tableAuthor;

		private global::Gtk.Image imageAuthor;

		private global::Gtk.ScrolledWindow scrolledwindowAuthor;

		private global::Gtk.Label labelAuthor;

		private global::Gtk.Label labelTabAuthor;

		private global::Gtk.Alignment alignmentTranslation;

		private global::Gtk.Table tableTranslation;

		private global::Gtk.Image imageTranslation;

		private global::Gtk.ScrolledWindow scrolledwindowTranslation;

		private global::Gtk.Label labelTranslation;

		private global::Gtk.Label labelTabTranslation;

		private global::Gtk.Alignment alignmentLisense;

		private global::Gtk.Table tableLisense;

		private global::Gtk.Image imageLisense;

		private global::Gtk.Label labelLisense;

		private global::Gtk.Label labelTabLisense;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CommBug.AboutWindow
			this.Name = "CommBug.AboutWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("关于本程序");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CommBug.AboutWindow.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "AboutWindow_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child AboutWindow_VBox.Gtk.Box+BoxChild
			this.notebookAboutWindow = new global::Gtk.Notebook ();
			this.notebookAboutWindow.CanFocus = true;
			this.notebookAboutWindow.Name = "notebookAboutWindow";
			this.notebookAboutWindow.CurrentPage = 3;
			// Container child notebookAboutWindow.Gtk.Notebook+NotebookChild
			this.alignmentInfo = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentInfo.Name = "alignmentInfo";
			this.alignmentInfo.BorderWidth = ((uint)(10));
			// Container child alignmentInfo.Gtk.Container+ContainerChild
			this.tableInfo = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tableInfo.Name = "tableInfo";
			this.tableInfo.RowSpacing = ((uint)(6));
			this.tableInfo.ColumnSpacing = ((uint)(6));
			// Container child tableInfo.Gtk.Table+TableChild
			this.imageInfo = new global::Gtk.Image ();
			this.imageInfo.Name = "imageInfo";
			this.imageInfo.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Dialog);
			this.tableInfo.Add (this.imageInfo);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.imageInfo]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableInfo.Gtk.Table+TableChild
			this.scrolledwindowInfo = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowInfo.CanFocus = true;
			this.scrolledwindowInfo.Name = "scrolledwindowInfo";
			this.scrolledwindowInfo.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowInfo.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.labelInfo = new global::Gtk.Label ();
			this.labelInfo.Name = "labelInfo";
			w3.Add (this.labelInfo);
			this.scrolledwindowInfo.Add (w3);
			this.tableInfo.Add (this.scrolledwindowInfo);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tableInfo[this.scrolledwindowInfo]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignmentInfo.Add (this.tableInfo);
			this.notebookAboutWindow.Add (this.alignmentInfo);
			// Notebook tab
			this.labelTabInfo = new global::Gtk.Label ();
			this.labelTabInfo.Name = "labelTabInfo";
			this.labelTabInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("信息(_I)");
			this.labelTabInfo.UseUnderline = true;
			this.notebookAboutWindow.SetTabLabel (this.alignmentInfo, this.labelTabInfo);
			this.labelTabInfo.ShowAll ();
			// Container child notebookAboutWindow.Gtk.Notebook+NotebookChild
			this.alignmentAuthor = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentAuthor.Name = "alignmentAuthor";
			this.alignmentAuthor.BorderWidth = ((uint)(10));
			// Container child alignmentAuthor.Gtk.Container+ContainerChild
			this.tableAuthor = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tableAuthor.Name = "tableAuthor";
			this.tableAuthor.RowSpacing = ((uint)(6));
			this.tableAuthor.ColumnSpacing = ((uint)(6));
			// Container child tableAuthor.Gtk.Table+TableChild
			this.imageAuthor = new global::Gtk.Image ();
			this.imageAuthor.Name = "imageAuthor";
			this.imageAuthor.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_person", global::Gtk.IconSize.Dialog);
			this.tableAuthor.Add (this.imageAuthor);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tableAuthor[this.imageAuthor]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableAuthor.Gtk.Table+TableChild
			this.scrolledwindowAuthor = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowAuthor.CanFocus = true;
			this.scrolledwindowAuthor.Name = "scrolledwindowAuthor";
			this.scrolledwindowAuthor.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowAuthor.Gtk.Container+ContainerChild
			global::Gtk.Viewport w10 = new global::Gtk.Viewport ();
			w10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.labelAuthor = new global::Gtk.Label ();
			this.labelAuthor.Name = "labelAuthor";
			w10.Add (this.labelAuthor);
			this.scrolledwindowAuthor.Add (w10);
			this.tableAuthor.Add (this.scrolledwindowAuthor);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableAuthor[this.scrolledwindowAuthor]));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignmentAuthor.Add (this.tableAuthor);
			this.notebookAboutWindow.Add (this.alignmentAuthor);
			global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebookAboutWindow[this.alignmentAuthor]));
			w15.Position = 1;
			// Notebook tab
			this.labelTabAuthor = new global::Gtk.Label ();
			this.labelTabAuthor.Name = "labelTabAuthor";
			this.labelTabAuthor.LabelProp = global::Mono.Unix.Catalog.GetString ("作者(_A)");
			this.labelTabAuthor.UseUnderline = true;
			this.notebookAboutWindow.SetTabLabel (this.alignmentAuthor, this.labelTabAuthor);
			this.labelTabAuthor.ShowAll ();
			// Container child notebookAboutWindow.Gtk.Notebook+NotebookChild
			this.alignmentTranslation = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentTranslation.Name = "alignmentTranslation";
			this.alignmentTranslation.BorderWidth = ((uint)(10));
			// Container child alignmentTranslation.Gtk.Container+ContainerChild
			this.tableTranslation = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tableTranslation.Name = "tableTranslation";
			this.tableTranslation.RowSpacing = ((uint)(6));
			this.tableTranslation.ColumnSpacing = ((uint)(6));
			// Container child tableTranslation.Gtk.Table+TableChild
			this.imageTranslation = new global::Gtk.Image ();
			this.imageTranslation.Name = "imageTranslation";
			this.imageTranslation.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_people", global::Gtk.IconSize.Dialog);
			this.tableTranslation.Add (this.imageTranslation);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableTranslation[this.imageTranslation]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableTranslation.Gtk.Table+TableChild
			this.scrolledwindowTranslation = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowTranslation.CanFocus = true;
			this.scrolledwindowTranslation.Name = "scrolledwindowTranslation";
			this.scrolledwindowTranslation.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowTranslation.Gtk.Container+ContainerChild
			global::Gtk.Viewport w17 = new global::Gtk.Viewport ();
			w17.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.labelTranslation = new global::Gtk.Label ();
			this.labelTranslation.Name = "labelTranslation";
			w17.Add (this.labelTranslation);
			this.scrolledwindowTranslation.Add (w17);
			this.tableTranslation.Add (this.scrolledwindowTranslation);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tableTranslation[this.scrolledwindowTranslation]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.alignmentTranslation.Add (this.tableTranslation);
			this.notebookAboutWindow.Add (this.alignmentTranslation);
			global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebookAboutWindow[this.alignmentTranslation]));
			w22.Position = 2;
			// Notebook tab
			this.labelTabTranslation = new global::Gtk.Label ();
			this.labelTabTranslation.Name = "labelTabTranslation";
			this.labelTabTranslation.LabelProp = global::Mono.Unix.Catalog.GetString ("翻译(_T)");
			this.labelTabTranslation.UseUnderline = true;
			this.notebookAboutWindow.SetTabLabel (this.alignmentTranslation, this.labelTabTranslation);
			this.labelTabTranslation.ShowAll ();
			// Container child notebookAboutWindow.Gtk.Notebook+NotebookChild
			this.alignmentLisense = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignmentLisense.Name = "alignmentLisense";
			this.alignmentLisense.BorderWidth = ((uint)(10));
			// Container child alignmentLisense.Gtk.Container+ContainerChild
			this.tableLisense = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tableLisense.Name = "tableLisense";
			this.tableLisense.RowSpacing = ((uint)(6));
			this.tableLisense.ColumnSpacing = ((uint)(6));
			// Container child tableLisense.Gtk.Table+TableChild
			this.imageLisense = new global::Gtk.Image ();
			this.imageLisense.Name = "imageLisense";
			this.imageLisense.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Dialog);
			this.tableLisense.Add (this.imageLisense);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tableLisense[this.imageLisense]));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableLisense.Gtk.Table+TableChild
			this.labelLisense = new global::Gtk.Label ();
			this.labelLisense.Name = "labelLisense";
			this.tableLisense.Add (this.labelLisense);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tableLisense[this.labelLisense]));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			this.alignmentLisense.Add (this.tableLisense);
			this.notebookAboutWindow.Add (this.alignmentLisense);
			global::Gtk.Notebook.NotebookChild w26 = ((global::Gtk.Notebook.NotebookChild)(this.notebookAboutWindow[this.alignmentLisense]));
			w26.Position = 3;
			// Notebook tab
			this.labelTabLisense = new global::Gtk.Label ();
			this.labelTabLisense.Name = "labelTabLisense";
			this.labelTabLisense.LabelProp = global::Mono.Unix.Catalog.GetString ("协议(_L)");
			this.labelTabLisense.UseUnderline = true;
			this.notebookAboutWindow.SetTabLabel (this.alignmentLisense, this.labelTabLisense);
			this.labelTabLisense.ShowAll ();
			w1.Add (this.notebookAboutWindow);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(w1[this.notebookAboutWindow]));
			w27.Position = 0;
			// Internal child CommBug.AboutWindow.ActionArea
			global::Gtk.HButtonBox w28 = this.ActionArea;
			w28.Name = "AboutWindow_ActionArea";
			w28.Spacing = 10;
			w28.BorderWidth = ((uint)(5));
			w28.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child AboutWindow_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-yes", global::Gtk.IconSize.Menu);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("确定(_O)");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.buttonOk.Add (w29);
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w28[this.buttonOk]));
			w37.Expand = false;
			w37.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 328;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
